// Fallback mock data when Supabase is not configured

export const MOCK_APPOINTMENTS = [
  {
    id: 'apt-1',
    user_id: 'any',
    service_id: 'svc-1',
    professional_id: 'pro-1',
    appointment_date: '2025-04-15',
    appointment_time: '14:00',
    status: 'confirmado',
    service_price: 120,
    booking_fee: 40,
    remaining_amount: 80,
    payment_status: 'aprovado',
    payment_id: 'pay-1',
    notes: null,
    trinks_appointment_id: null,
    created_at: '2025-04-01T10:00:00Z',
    updated_at: '2025-04-01T10:00:00Z',
  },
  {
    id: 'apt-2',
    user_id: 'any',
    service_id: 'svc-4',
    professional_id: 'pro-2',
    appointment_date: '2025-04-20',
    appointment_time: '10:00',
    status: 'pendente_pagamento',
    service_price: 90,
    booking_fee: 40,
    remaining_amount: 50,
    payment_status: 'pendente',
    payment_id: null,
    notes: null,
    trinks_appointment_id: null,
    created_at: '2025-04-05T11:00:00Z',
    updated_at: '2025-04-05T11:00:00Z',
  },
];
